version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # For Linux
      - "host.docker.internal:192.168.65.2"   # For macOS (Docker Desktop)